export const SITE = {
  name: "Omega CSA Engenharia",
  shortName: "Omega CSA",
  url: "https://omegacsa.com.br",
  tagline: "Soluções integradas em engenharia para obras públicas, privadas, industriais e ambientais.",
  description:
    "Soluções integradas em engenharia para obras públicas, privadas, industriais e ambientais. Projetos, fiscalização e consultoria especializada em Campos dos Goytacazes, RJ.",
  email: "omega@omegacsa.com.br",
  emailAlt: "omegaengenharia.csa@gmail.com",
  phone: "(22) 3025-7633",
  phoneAlt: "(22) 99964-4607",
  address: {
    street: "Rua Cel. Pache Faria, 213",
    neighborhood: "Pq. Nova Brasília",
    city: "Campos dos Goytacazes",
    state: "RJ",
    cep: "28.055-230",
    full: "Rua Cel. Pache Faria, 213 — Pq. Nova Brasília, Campos dos Goytacazes — RJ",
  },
  supportOffices: ["Carapebus", "Nova Iguaçu", "São Francisco de Itabapoana"],
  social: {
    whatsapp: "5522999644607",
  },
  team: {
    engineer: {
      name: "Maxuel Bernardes Donato",
      role: "Diretor Técnico / Administrativo",
      crea: "2009101529",
      titles: [
        "Engenheiro Civil",
        "Engenheiro de Segurança do Trabalho",
        "Engenheiro Sanitarista e Ambiental Esp.",
        "Engenheiro de Avaliações e Perícias Esp.",
        "Engenheiro de Geotecnia Esp.",
        "Engenheiro de Cartografia Esp.",
        "MSc. Engenharia Ambiental Profissional — Recursos Hídricos",
        "Doutorando em Modelagem e Tecnologia em Recursos Hídricos",
      ],
    },
    director: {
      name: "Lecyana R. Silva Donato",
      role: "Chefe Administradora",
      degree: "Ciências Contábeis",
    },
    lawyer: {
      name: "Israel B. Donato",
      role: "Advogado",
    },
    extended: [
      "Engenheiros Civis",
      "Engenheiros Sanitaristas e Ambientais",
      "Engenheiro Químico",
      "Engenheiro Eletricista",
      "Engenheiro Mecânico",
      "Geólogo",
    ],
  },
} as const;

export const STATS = [
  { value: "15+", label: "Anos de experiência" },
  { value: "200+", label: "Projetos entregues" },
  { value: "100%", label: "Compromisso técnico" },
  { value: "RJ", label: "Sede no Norte Fluminense" },
] as const;

export const AREAS = [
  {
    slug: "engenharia-civil",
    title: "Engenharia Civil, Arquitetura e Urbanismo",
    shortDesc: "Projetos civis, arquitetônicos, urbanísticos e acompanhamento técnico de obras.",
    icon: "building",
    services: [
      "Projetos arquitetônicos residenciais, comerciais, institucionais e industriais",
      "Projetos de reformas, ampliações, adequações e revitalizações",
      "Projetos de unidades escolares, hospitalares, administrativas e equipamentos públicos",
      "Projetos de urbanização de praças, parques, quadras, áreas de lazer e espaços públicos",
      "Projetos de paisagismo e requalificação urbana",
      "Projetos de acessibilidade e adequação de edificações",
      "Projetos de infraestrutura urbana",
      "Projetos de loteamentos e condomínios",
      "Projetos de vias urbanas, calçadas, ciclovias, estacionamentos e acessos",
      "Projetos de terraplanagem, pavimentação e drenagem superficial",
      "Projetos de sinalização viária horizontal e vertical",
      "Orçamentos, memoriais descritivos, cronogramas e especificações técnicas",
      "Fiscalização, supervisão e acompanhamento técnico de obras",
      "Compatibilização de projetos civis, elétricos, hidrossanitários e estruturais",
    ],
  },
  {
    slug: "projetos-estruturais",
    title: "Projetos Estruturais",
    shortDesc: "Estruturas de concreto armado, metálicas, fundações e diagnóstico de patologias.",
    icon: "layers",
    services: [
      "Projetos estruturais de edificações em concreto armado",
      "Projetos de estruturas metálicas",
      "Projetos de fundações",
      "Projetos de contenção, muros de arrimo, cortinas e taludes",
      "Projetos de pontes, viadutos, passarelas, bueiros e galerias",
      "Projetos estruturais para reservatórios, tanques e estações de tratamento",
      "Reforço estrutural e recuperação de estruturas existentes",
      "Avaliação de patologias estruturais",
      "Inspeção, diagnóstico e plano de manutenção de estruturas",
      "Projetos de demolição técnica e escoramento",
      "Laudos estruturais para edificações, condomínios e equipamentos públicos",
    ],
  },
  {
    slug: "hidrossanitaria",
    title: "Engenharia Hidrossanitária",
    shortDesc: "Instalações hidráulicas, sanitárias, pluviais e sistemas de pressurização predial.",
    icon: "droplets",
    services: [
      "Projetos de instalações hidráulicas prediais",
      "Projetos de instalações sanitárias",
      "Projetos de águas pluviais em edificações",
      "Projetos de reservatórios, caixas d'água, cisternas e sistemas de pressurização",
      "Projetos de reuso de água",
      "Projetos de aproveitamento de água de chuva",
      "Projetos de redes internas de esgoto",
      "Projetos de redes de abastecimento de água",
      "Projetos de combate a incêndio com sistemas hidráulicos",
      "Compatibilização de instalações com arquitetura, estrutura e elétrica",
    ],
  },
  {
    slug: "sanitaria-ambiental",
    title: "Engenharia Sanitária e Ambiental",
    shortDesc: "Drenagem urbana, saneamento, ETE/ETA, licenciamento ambiental e gestão hídrica.",
    icon: "leaf",
    services: [
      "Estudos e projetos de microdrenagem e macrodrenagem urbana",
      "Estudos hidrológicos e hidráulicos",
      "Modelagem de áreas inundáveis",
      "Projetos de manejo de águas pluviais",
      "Projetos de canais, galerias, bueiros, travessias e dispositivos de drenagem",
      "Monitoramento de ambientes costeiros (lagos, rios e afins)",
      "Estudo e projeto para sistemas de amortização de cheias e alagamentos",
      "Monitoramento e gestão de corpos hídricos",
      "Projetos de sistemas de esgotamento sanitário",
      "Projetos de redes coletoras de esgoto",
      "Projetos de estações elevatórias de esgoto",
      "Projetos de estações de tratamento de esgoto — ETE",
      "Projetos de estações de tratamento de água — ETA",
      "Projetos de sistemas de abastecimento de água",
      "Estudos de concepção em saneamento",
      "Manejo de resíduos sólidos urbanos",
      "Estudos para recuperação de áreas degradadas — PRAD",
      "Estudos de áreas contaminadas",
      "Avaliação de impacto ambiental",
      "Elaboração de EIA/RIMA, RCA, PCA, relatórios ambientais e estudos correlatos",
      "Licenciamento ambiental municipal, estadual e federal",
      "Outorga de uso de recursos hídricos",
      "Relatórios técnicos para órgãos ambientais",
      "Instalação de poços de monitoramento, multinível e vapor",
    ],
  },
  {
    slug: "seguranca-do-trabalho",
    title: "Segurança do Trabalho",
    shortDesc: "Engenharia de segurança, gestão de riscos, laudos de insalubridade e NRs.",
    icon: "shield",
    services: [
      "Projetos de segurança do trabalho para obras e atividades industriais",
      "Plano de gerenciamento de riscos — PGR/GRO",
      "Laudos técnicos de insalubridade e periculosidade",
      "Laudo técnico das condições ambientais do trabalho — LTCAT",
      "Plano de redução de ruído",
      "Mapeamento de ruído e estudos acústicos ocupacionais",
      "Projetos de enclausuramento acústico e controle de ruído",
      "Projetos de demolição segura",
      "Análise preliminar de riscos — APR",
      "Procedimentos técnicos para trabalho em altura, espaço confinado e eletricidade",
      "Adequações às normas de segurança em canteiros de obras",
      "Projetos de prevenção e combate a incêndio e pânico",
      "Rotas de fuga, sinalização de emergência e planos de abandono",
      "Avaliação de riscos em instalações industriais",
      "Consultoria para atendimento às normas regulamentadoras",
    ],
  },
  {
    slug: "geotecnia-barragens",
    title: "Geotecnia, Barragens e Segurança de Estruturas",
    shortDesc: "Estudos geotécnicos, contenção de encostas, segurança de barragens e instrumentação.",
    icon: "mountain",
    services: [
      "Estudos geotécnicos para obras civis",
      "Sondagem de terreno e investigação geotécnica",
      "Pareceres técnicos de fundações",
      "Projetos de contenção de encostas, taludes e margens de rios",
      "Estudos de estabilidade de taludes",
      "Projetos de drenagem profunda e superficial",
      "Laudos de inspeção regular e especial de barragens",
      "Plano de Segurança de Barragens",
      "Plano de Ação de Emergência — PAE",
      "Diagnóstico de anomalias em barragens e estruturas de contenção",
      "Projetos de manutenção, recuperação e melhorias em estruturas geotécnicas",
      "Monitoramento e instrumentação de estruturas",
      "Avaliação de risco geotécnico em áreas urbanas, rurais e industriais",
      "Instalação de poços de monitoramento, multinível e vapor",
    ],
  },
  {
    slug: "engenharia-mecanica",
    title: "Engenharia Mecânica",
    shortDesc: "Projetos de bombas, equipamentos operacionais, ventilação e climatização.",
    icon: "settings",
    services: [
      "Projetos de casas de bombas",
      "Dimensionamento de bombas, conjuntos motobomba e sistemas de recalque",
      "Projetos de equipamentos operacionais para ETE, ETA e indústrias",
      "Projetos de tubulações industriais",
      "Projetos de sistemas de ventilação e exaustão",
      "Projetos de climatização",
      "Especificação técnica de equipamentos mecânicos",
      "Projetos de sistemas de tratamento com equipamentos eletromecânicos",
      "Estudos de eficiência operacional de sistemas de bombeamento",
      "Adequação de máquinas e equipamentos às normas de segurança",
      "Memorial técnico para aquisição, instalação e operação de equipamentos",
    ],
  },
  {
    slug: "cartografia-topografia",
    title: "Cartografia, Geodésia, Topografia e Geoprocessamento",
    shortDesc: "Levantamentos topográficos, georreferenciamento, drones e regularização fundiária.",
    icon: "map",
    services: [
      "Levantamento planialtimétrico",
      "Levantamento cadastral urbano e rural",
      "Georreferenciamento de imóveis rurais",
      "Regularização fundiária urbana e rural",
      "Cadastro Ambiental Rural — CAR",
      "CCIR, ITR e apoio documental para regularização rural",
      "Retificação de área",
      "Desmembramento, remembramento e parcelamento de solo",
      "Aerofotogrametria com drones",
      "Mapeamento de áreas urbanas, rurais, ambientais e industriais",
      "Geoprocessamento e elaboração de mapas temáticos",
      "Cadastro técnico multifinalitário",
      "Locação de obras",
      "As built de obras e instalações existentes",
      "Apoio técnico para usucapião, inventários e processos judiciais",
    ],
  },
  {
    slug: "avaliacoes-pericias",
    title: "Avaliações, Perícias e Inspeções",
    shortDesc: "Laudos técnicos, perícias judiciais, inspeção predial e vídeo inspeção robotizada.",
    icon: "search",
    services: [
      "Inspeção predial em edificações residenciais, comerciais e industriais",
      "Inspeção em condomínios e prédios",
      "Laudos de vistoria técnica",
      "Vistoria cautelar de vizinhança",
      "Avaliação de imóveis urbanos e rurais",
      "Avaliação de benfeitorias, terrenos, glebas e edificações",
      "Perícias judiciais e extrajudiciais",
      "Assistência técnica em processos judiciais",
      "Laudos sobre vícios construtivos",
      "Laudos sobre patologias em edificações",
      "Análise de problemas de habitabilidade em imóveis financiados ou adquiridos",
      "Avaliação de infiltrações, trincas, fissuras, recalques e problemas estruturais",
      "Laudos para recebimento de obras e entrega de unidades imobiliárias",
      "Parecer técnico para condomínios, construtoras, seguradoras e escritórios de advocacia",
      "Vídeo inspeção robotizada em redes de esgoto e galerias de águas pluviais",
      "Inspeção interna de tubulações de pequeno, médio e grande diâmetro",
      "Diagnóstico de infiltrações, raízes, deslocamentos, rupturas e obstruções",
      "Verificação de ligações irregulares",
      "Avaliação das condições estruturais e operacionais da rede",
      "Mapeamento da condição da rede para priorização de investimentos",
    ],
  },
  {
    slug: "engenharia-eletrica",
    title: "Engenharia Elétrica",
    shortDesc: "Projetos elétricos prediais, industriais, energia solar, SPDA e eficiência energética.",
    icon: "zap",
    services: [
      "Projetos elétricos residenciais, comerciais, prediais e industriais",
      "Projetos de baixa e média tensão",
      "Projetos de entrada de energia e subestações",
      "Projetos de quadros elétricos e distribuição",
      "Projetos de iluminação interna, externa e pública",
      "Projetos de eficiência energética",
      "Projetos de energia solar fotovoltaica",
      "Projetos de aterramento e SPDA — Sistema de Proteção contra Descargas Atmosféricas",
      "Laudos elétricos e adequação às normas de segurança elétrica",
      "Projetos de automação, telemetria e controle para ETE, ETA e sistemas de bombeamento",
      "Infraestrutura elétrica para climatização, bombas, equipamentos e sistemas industriais",
    ],
  },
  {
    slug: "modelagem-tecnologia",
    title: "Engenharia de Modelagem e Tecnologia",
    shortDesc: "BIM, escaneamento 3D a laser, drones, vídeo inspeção e modelagem hidrodinâmica.",
    icon: "cpu",
    services: [
      "Topografia de precisão com equipamentos de última geração",
      "Mapeamento de redes e instalações subterrâneas",
      "Escaneamento a laser 3D de alta precisão para estruturas existentes",
      "Modelagem BIM sobre nuvem de pontos",
      "Mapeamento e voos com drones (aerofotogrametria)",
      "Modelagem de dispersão de efluentes líquidos em corpos hídricos",
      "Estudos de lançamento de efluentes tratados e avaliação de zona de mistura",
      "Simulação de plumas de contaminação em águas superficiais e subterrâneas",
      "Modelagem de transporte de contaminantes no solo e na água subterrânea",
      "Avaliação de áreas contaminadas e mapeamento de plumas",
      "Modelagem hidrológica de chuvas intensas",
      "Modelagem hidráulica de canais, rios, galerias e redes de drenagem",
      "Simulação de manchas de inundação e estudos de cotas de cheia",
      "Modelagem de bacias de retenção e detenção",
      "Avaliação de capacidade hidráulica de galerias existentes",
      "Estudos de autodepuração de corpos d'água",
      "Monitoramento ambiental georreferenciado",
    ],
  },
] as const;

export const SERVICES = [
  {
    slug: "projetos-tecnicos",
    title: "Projetos Técnicos",
    shortDesc: "Elaboração de projetos em todas as disciplinas: civil, estrutural, hidrossanitário, ambiental, elétrico e mecânico.",
    description:
      "Desenvolvemos projetos executivos completos em todas as disciplinas de engenharia. Da concepção ao detalhamento final, com precisão técnica, compatibilização interdisciplinar e conformidade com normas ABNT e legislação vigente.",
    icon: "file-text",
  },
  {
    slug: "fiscalizacao-supervisao",
    title: "Fiscalização e Supervisão",
    shortDesc: "Acompanhamento técnico de obras públicas e privadas, controle de qualidade e relatórios de progresso.",
    description:
      "Atuamos como representantes técnicos do contratante na fiscalização e supervisão de obras, garantindo conformidade com projetos, especificações técnicas e prazos. Emitimos relatórios periódicos detalhados.",
    icon: "hard-hat",
  },
  {
    slug: "laudos-pericias",
    title: "Laudos e Perícias",
    shortDesc: "Laudos técnicos, vistorias, avaliações patrimoniais e perícias judiciais e extrajudiciais.",
    description:
      "Elaboração de laudos técnicos para vistorias de imóveis, avaliações patrimoniais, perícias judiciais e extrajudiciais. Profissionais habilitados no CREA com atuação em todo o estado do Rio de Janeiro.",
    icon: "file-search",
  },
  {
    slug: "consultoria",
    title: "Consultoria Especializada",
    shortDesc: "Diagnóstico técnico, otimização de sistemas, pareceres e assessoria especializada em engenharia.",
    description:
      "Oferecemos consultoria técnica especializada para diagnóstico de problemas, otimização de sistemas existentes, emissão de pareceres e assessoria em decisões de engenharia para empresas, órgãos públicos e particulares.",
    icon: "lightbulb",
  },
  {
    slug: "gerenciamento-obras",
    title: "Gerenciamento de Obras",
    shortDesc: "Planejamento, cronograma físico-financeiro, controle de custos e gestão de contratos.",
    description:
      "Gerenciamento integral de obras: planejamento, cronograma físico-financeiro, controle de qualidade, gestão de contratos e relatórios de progresso. Aplicamos metodologias modernas de gestão para garantir prazo, custo e qualidade.",
    icon: "hard-hat",
  },
  {
    slug: "licenciamento-ambiental",
    title: "Licenciamentos e Estudos Ambientais",
    shortDesc: "EIA/RIMA, outorgas, licenciamento ambiental e estudos correlatos junto a órgãos competentes.",
    description:
      "Elaboramos e acompanhamos processos de licenciamento ambiental municipal, estadual e federal. EIA/RIMA, RCA, PCA, outorga de uso de recursos hídricos e toda a documentação técnica necessária para aprovação em órgãos reguladores.",
    icon: "leaf",
  },
] as const;

export const NAV_LINKS = [
  { label: "Início", href: "/" },
  { label: "A Empresa", href: "/sobre" },
  { label: "Áreas de Atuação", href: "/areas-de-atuacao" },
  { label: "Portfólio", href: "/portfolio" },
  { label: "Serviços Técnicos", href: "/servicos" },
  { label: "Clientes e Atestados", href: "/clientes" },
  { label: "Contato", href: "/contato" },
] as const;
